//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Ashish_Garg
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_Ashish_GargEntities : DbContext
    {
        public DB_Ashish_GargEntities()
            : base("name=DB_Ashish_GargEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCustomer> tblCustomers { get; set; }
        public virtual DbSet<tblServiceProvider> tblServiceProviders { get; set; }
        public virtual DbSet<tblServiceProviderCity> tblServiceProviderCities { get; set; }
    }
}
